sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML Document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: CSS File
    deactivate server

    browser->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser executes the callback function that renders the note

    browser->> server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "Hello from TEJ", "date": "2025-07-27" }, ... ]
    deactivate server


    browser->> server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa

    Note right of browser: POST request to address new_note_spa with JSON data
    
    activate server
    server-->> browser: message: note created (201 status code)

    Note right of browser: Browser stays on the same page 
    Note left of server: JavaScript code fetch the new note data from the server
